spring:
  application:
    name: url-shortener
  datasource:
    url: jdbc:h2:mem:url-shortener
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
